# 27 MHz board oscillator
create_clock -name clk_27mhz -period 37.037 [get_ports {clk_27mhz}]

# USB HID host clock (12 MHz, generated by second rPLL in tang20k_sbc_top)
# usb_dm / usb_dp are bit-bang GPIO; no setup/hold constraints needed.
create_clock -name usb_clk -period 83.333 [get_nets {usb_clk}]

# The two clock domains (27 MHz system and 12 MHz USB) are asynchronous.
# All crossings use toggle synchronisers (2-FF), so declare them false paths.
set_false_path -from [get_clocks {usb_clk}] -to [get_clocks {clk_27mhz}]
set_false_path -from [get_clocks {clk_27mhz}] -to [get_clocks {usb_clk}]
