#!/usr/bin/env python3
"""Convert a big-endian 68000 binary into the System16 boot-ROM package."""

from __future__ import annotations

import argparse
from pathlib import Path


ROM_WORDS = 512
FILL_WORD = 0x4E71


def render_package(data: bytes) -> str:
    if len(data) > ROM_WORDS * 2:
        raise ValueError(f"boot image exceeds {ROM_WORDS * 2} bytes")
    if len(data) % 2:
        raise ValueError("68000 boot image must contain an even number of bytes")

    lines = [
        "-- Generated by tools/bin_to_boot_rom_vhdl.py; do not edit by hand.",
        "library ieee;",
        "use ieee.std_logic_1164.all;",
        "",
        "package sys16_boot_rom_image_pkg is",
        "  type sys16_boot_rom_image_t is array (0 to 511) of std_logic_vector(15 downto 0);",
        "  constant SYS16_BOOT_ROM_IMAGE : sys16_boot_rom_image_t := (",
    ]

    for index in range(0, len(data), 2):
        word = (data[index] << 8) | data[index + 1]
        lines.append(f'    {index // 2:3d} => x"{word:04X}",')

    lines.extend(
        [
            f'    others => x"{FILL_WORD:04X}"',
            "  );",
            "end package;",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("image", type=Path, help="Input binary")
    parser.add_argument("output", type=Path, help="Generated VHDL package")
    args = parser.parse_args()

    try:
        generated = render_package(args.image.read_bytes())
    except (OSError, ValueError) as exc:
        raise SystemExit(str(exc)) from exc

    if args.output.exists() and args.output.read_text(encoding="ascii") == generated:
        print(f"unchanged: {args.output}")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    temporary = args.output.with_suffix(args.output.suffix + ".tmp")
    temporary.write_text(generated, encoding="ascii", newline="\n")
    temporary.replace(args.output)
    print(f"updated: {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
