#!/usr/bin/env python3
"""Build a small FAT16 SD-card image containing contiguous .d64 files.

The MiSTer C64 SD backend can read a normal packed .d64 file when it knows the
file's first LBA.  This helper creates a deterministic FAT16 card image, writes
each input .d64 contiguously, and prints the start LBA for each file.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import struct


SECTOR = 512
D64_SIZE = 174_848
SELECTOR_KEYS = "123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"


def parse_size(text: str) -> int:
    value = text.strip().lower()
    mult = 1
    if value.endswith("k"):
        mult = 1024
        value = value[:-1]
    elif value.endswith("m"):
        mult = 1024 * 1024
        value = value[:-1]
    elif value.endswith("g"):
        mult = 1024 * 1024 * 1024
        value = value[:-1]
    return int(value, 0) * mult


def short_name(name: str) -> bytes:
    stem, dot, ext = name.upper().rpartition(".")
    if not dot:
        stem, ext = name.upper(), ""
    clean_stem = "".join(ch for ch in stem if ch.isalnum() or ch in "_-$~")
    clean_ext = "".join(ch for ch in ext if ch.isalnum())
    return (clean_stem[:8].ljust(8) + clean_ext[:3].ljust(3)).encode("ascii")


def selector_display_name(short: str) -> str:
    stem = short[:8].rstrip()
    ext = short[8:11].rstrip()
    return f"{stem}.{ext}" if ext else stem


def asm_string(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '""') + '"'


def write_selector_table(path: Path, files: list[dict[str, object]]) -> None:
    if len(files) > len(SELECTOR_KEYS):
        raise ValueError(
            f"selector supports at most {len(SELECTOR_KEYS)} entries, got {len(files)}"
        )

    lines: list[str] = [
        "; Generated by tools/d64/make_fat16_d64_card.py.",
        "; Do not edit by hand unless you also keep the FAT16 image LBAs in sync.",
        "",
        f"ENTRY_COUNT = {len(files)}",
        "",
        "menu:",
    ]

    for index, item in enumerate(files):
        key = SELECTOR_KEYS[index]
        display = selector_display_name(str(item["short_name"]))
        lines.append(f"        .byte {asm_string(key + ' ' + display)}, $0D")

    if len(files) <= 9:
        prompt = f"PRESS 1-{len(files)}"
    else:
        last_key = SELECTOR_KEYS[len(files) - 1]
        prompt = f"PRESS 1-9/A-{last_key}"
    lines.extend([
        "        .byte $0D",
        f"        .byte {asm_string(prompt)}, $0D, 0",
        "",
    ])

    for index, item in enumerate(files):
        display = selector_display_name(str(item["short_name"]))
        lines.extend([
            f"name{index}:",
            f"        .byte {asm_string(display)}, 0",
        ])

    lines.extend(["", "name_ptrs:"])
    ptrs = ", ".join(f"name{index}" for index in range(len(files)))
    lines.append(f"        .word {ptrs}" if ptrs else "        .word 0")

    lines.extend(["", "lba_table:"])
    for item in files:
        display = selector_display_name(str(item["short_name"]))
        lba = int(item["start_lba"])
        b0 = lba & 0xFF
        b1 = (lba >> 8) & 0xFF
        b2 = (lba >> 16) & 0xFF
        b3 = (lba >> 24) & 0xFF
        lines.append(
            f"        .byte ${b0:02X}, ${b1:02X}, ${b2:02X}, ${b3:02X}   "
            f"; {display} start_lba={lba}"
        )

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="ascii")


class Fat16Builder:
    def __init__(
        self,
        *,
        image_size: int,
        sectors_per_cluster: int = 4,
        reserved_sectors: int = 1,
        root_entries: int = 512,
        num_fats: int = 2,
        partition_start_lba: int = 2048,
        superfloppy: bool = False,
    ) -> None:
        if image_size % SECTOR:
            raise ValueError("image size must be a multiple of 512 bytes")
        self.image_size = image_size
        self.spc = sectors_per_cluster
        self.reserved = reserved_sectors
        self.root_entries = root_entries
        self.num_fats = num_fats
        self.part_start = 0 if superfloppy else partition_start_lba
        self.superfloppy = superfloppy
        self.files: list[tuple[str, bytes]] = []
        self.meta: dict[str, object] = {}

    def add_file(self, name: str, data: bytes) -> None:
        if len(data) != D64_SIZE:
            raise ValueError(f"{name}: expected {D64_SIZE} bytes, got {len(data)}")
        new_short = short_name(name)
        for old_name, _ in self.files:
            if short_name(old_name) == new_short:
                display = selector_display_name(new_short.decode("ascii"))
                raise ValueError(
                    f"{name}: FAT 8.3 name collides with {old_name} as {display}"
                )
        self.files.append((name, data))

    def build(self) -> bytes:
        root_dir_sectors = (self.root_entries * 32 + SECTOR - 1) // SECTOR
        bytes_per_cluster = self.spc * SECTOR

        layout = []
        next_cluster = 2
        for name, data in self.files:
            clusters = (len(data) + bytes_per_cluster - 1) // bytes_per_cluster
            layout.append((name, data, next_cluster, clusters))
            next_cluster += clusters

        data_clusters = next_cluster - 2
        min_fat_entries = next_cluster
        sectors_per_fat = max(1, (min_fat_entries * 2 + SECTOR - 1) // SECTOR)
        data_start = self.reserved + self.num_fats * sectors_per_fat + root_dir_sectors
        min_volume_sectors = data_start + data_clusters * self.spc

        available_card_sectors = self.image_size // SECTOR
        volume_sectors = available_card_sectors - self.part_start
        if volume_sectors < min_volume_sectors:
            need = (self.part_start + min_volume_sectors) * SECTOR
            raise ValueError(f"image too small; need at least {need} bytes")

        cluster_count = (volume_sectors - data_start) // self.spc
        if cluster_count < 4085 or cluster_count >= 65525:
            raise ValueError(
                "geometry is not FAT16-sized; adjust --size/--spc "
                f"(cluster_count={cluster_count})"
            )

        fat = bytearray(sectors_per_fat * SECTOR)

        def set_fat(cluster: int, value: int) -> None:
            struct.pack_into("<H", fat, cluster * 2, value & 0xFFFF)

        set_fat(0, 0xFFF8)
        set_fat(1, 0xFFFF)
        for _, _, first, clusters in layout:
            for k in range(clusters):
                cluster = first + k
                set_fat(cluster, 0xFFFF if k == clusters - 1 else cluster + 1)

        volume = bytearray(volume_sectors * SECTOR)
        boot = bytearray(SECTOR)
        boot[0:3] = b"\xeb\x3c\x90"
        boot[3:11] = b"MSDOS5.0"
        struct.pack_into("<H", boot, 11, SECTOR)
        boot[13] = self.spc
        struct.pack_into("<H", boot, 14, self.reserved)
        boot[16] = self.num_fats
        struct.pack_into("<H", boot, 17, self.root_entries)
        if volume_sectors <= 0xFFFF:
            struct.pack_into("<H", boot, 19, volume_sectors)
            struct.pack_into("<I", boot, 32, 0)
        else:
            struct.pack_into("<H", boot, 19, 0)
            struct.pack_into("<I", boot, 32, volume_sectors)
        boot[21] = 0xF8
        struct.pack_into("<H", boot, 22, sectors_per_fat)
        struct.pack_into("<H", boot, 24, 63)
        struct.pack_into("<H", boot, 26, 255)
        struct.pack_into("<I", boot, 28, self.part_start)
        boot[36] = 0x80
        boot[38] = 0x29
        struct.pack_into("<I", boot, 39, 0x20260702)
        boot[43:54] = b"MISTER D64 "
        boot[54:62] = b"FAT16   "
        boot[510] = 0x55
        boot[511] = 0xAA
        volume[0:SECTOR] = boot

        for n in range(self.num_fats):
            base = (self.reserved + n * sectors_per_fat) * SECTOR
            volume[base : base + len(fat)] = fat

        root_base = (self.reserved + self.num_fats * sectors_per_fat) * SECTOR
        for index, (name, data, first, _) in enumerate(layout):
            entry = bytearray(32)
            entry[0:11] = short_name(name)
            entry[11] = 0x20
            struct.pack_into("<H", entry, 26, first)
            struct.pack_into("<I", entry, 28, len(data))
            off = root_base + index * 32
            volume[off : off + 32] = entry

            data_base = (data_start + (first - 2) * self.spc) * SECTOR
            volume[data_base : data_base + len(data)] = data

        if self.superfloppy:
            card = bytearray(volume)
        else:
            card = bytearray(self.image_size)
            mbr = bytearray(SECTOR)
            part = bytearray(16)
            part[4] = 0x06
            struct.pack_into("<I", part, 8, self.part_start)
            struct.pack_into("<I", part, 12, volume_sectors)
            mbr[446:462] = part
            mbr[510] = 0x55
            mbr[511] = 0xAA
            card[0:SECTOR] = mbr
            start = self.part_start * SECTOR
            card[start : start + len(volume)] = volume

        self.meta = {
            "partition_start_lba": self.part_start,
            "sectors_per_cluster": self.spc,
            "reserved_sectors": self.reserved,
            "root_dir_sectors": root_dir_sectors,
            "sectors_per_fat": sectors_per_fat,
            "data_start_lba": self.part_start + data_start,
            "files": [
                {
                    "name": name,
                    "short_name": short_name(name).decode("ascii"),
                    "first_cluster": first,
                    "start_lba": self.part_start + data_start + (first - 2) * self.spc,
                }
                for name, _, first, _ in layout
            ],
        }
        return bytes(card)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("-o", "--output", type=Path, required=True)
    parser.add_argument("d64", nargs="+", type=Path, help="35-track .d64 files")
    parser.add_argument("--size", default="32M", help="card image size")
    parser.add_argument("--spc", type=int, default=4, help="sectors per cluster")
    parser.add_argument("--superfloppy", action="store_true", help="write BPB at LBA 0")
    parser.add_argument("--partition-start", type=int, default=2048)
    parser.add_argument(
        "--selector-table",
        type=Path,
        help="also write a ca65 include table for sw/c64_sd_d64_select.s",
    )
    args = parser.parse_args()

    builder = Fat16Builder(
        image_size=parse_size(args.size),
        sectors_per_cluster=args.spc,
        partition_start_lba=args.partition_start,
        superfloppy=args.superfloppy,
    )
    for path in args.d64:
        builder.add_file(path.name, path.read_bytes())

    image = builder.build()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_bytes(image)
    if args.selector_table:
        write_selector_table(args.selector_table, builder.meta["files"])  # type: ignore[arg-type]

    print(f"wrote {args.output} ({len(image)} bytes)")
    if args.selector_table:
        print(f"wrote selector table {args.selector_table}")
    print(
        "geometry: "
        f"part_lba={builder.meta['partition_start_lba']} "
        f"spc={builder.meta['sectors_per_cluster']} "
        f"spf={builder.meta['sectors_per_fat']} "
        f"data_lba={builder.meta['data_start_lba']}"
    )
    for item in builder.meta["files"]:  # type: ignore[index]
        print(
            f"{item['name']}: short={item['short_name']!r} "
            f"cluster={item['first_cluster']} start_lba={item['start_lba']}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
