#!/usr/bin/env python3
"""Generate the built-in boot ROM VHDL package from a 16 KiB binary image."""

from __future__ import annotations

import argparse
from pathlib import Path


def parse_int(value: str) -> int:
    return int(value, 0)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("image", help="Input binary ROM image")
    parser.add_argument("-o", "--output", required=True, help="Output VHDL package")
    parser.add_argument("--size", type=parse_int, default=0x4000, help="ROM size")
    parser.add_argument("--constant", default="BOOT_ROM_EHBASIC", help="Constant name")
    args = parser.parse_args()

    data = Path(args.image).read_bytes()
    if len(data) > args.size:
        raise SystemExit(f"{args.image} is larger than {args.size:#x} bytes")
    data = data + bytes([0xEA] * (args.size - len(data)))

    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)

    with out.open("w", encoding="ascii", newline="\n") as f:
        f.write("-- Generated by tools/bin_to_vhdl_rom_pkg.py; do not edit by hand.\n")
        f.write("library ieee;\n")
        f.write("use ieee.std_logic_1164.all;\n\n")
        f.write("use work.sbc_pkg.all;\n\n")
        f.write("package boot_rom_init_pkg is\n")
        f.write(f"  type boot_rom_t is array (0 to {args.size - 1}) of data_t;\n")
        f.write(f"  constant {args.constant} : boot_rom_t := (\n")
        for offset, value in enumerate(data):
            suffix = "," if offset != len(data) - 1 else ""
            f.write(f"    {offset:5d} => x\"{value:02X}\"{suffix}\n")
        f.write("  );\n")
        f.write("end package;\n")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
