#!/usr/bin/env python3
"""Generate rtl/c64/c64_roms.vhd from the original C64 ROM images.

Reads the three Commodore ROMs from roms/c64/ and emits a single VHDL file
with three synchronous block-ROM entities (basic_rom, kernal_rom, chargen_rom),
each carrying its image as an embedded constant array. This matches the repo
convention (char_rom / EhBASIC) of self-contained ROMs rather than file-loaded
ones, which keeps the build portable between GHDL and Gowin gw_sh.

Usage:
    python tools/build_c64_roms.py
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ROM_DIR = ROOT / "roms" / "c64"
OUT = ROOT / "rtl" / "c64" / "c64_roms.vhd"

# (entity name, source file, expected size in bytes)
ROMS = [
    ("basic_rom", "BASIC.ROM", 0x2000),    # $A000-$BFFF
    ("kernal_rom", "KERNAL.ROM", 0x2000),  # $E000-$FFFF
    ("chargen_rom", "CHAR.ROM", 0x1000),   # char generator (banked under I/O)
]


def addr_width(size: int) -> int:
    w = 0
    while (1 << w) < size:
        w += 1
    return w


def emit_rom(name: str, data: bytes, dual: bool = False) -> str:
    size = len(data)
    aw = addr_width(size)
    lines: list[str] = []
    lines.append(f"-- {name}: {size} bytes ({aw}-bit address), generated by tools/build_c64_roms.py")
    lines.append("library ieee;")
    lines.append("use ieee.std_logic_1164.all;")
    lines.append("use ieee.numeric_std.all;")
    lines.append("")
    lines.append(f"entity {name} is")
    lines.append("  port (")
    lines.append("    clk    : in  std_logic;")
    if dual:
        # Two independent synchronous read ports (CPU + VIC share the chargen).
        lines.append(f"    a_addr : in  std_logic_vector({aw - 1} downto 0);")
        lines.append("    a_dout : out std_logic_vector(7 downto 0);")
        lines.append(f"    b_addr : in  std_logic_vector({aw - 1} downto 0);")
        lines.append("    b_dout : out std_logic_vector(7 downto 0)")
    else:
        lines.append(f"    addr   : in  std_logic_vector({aw - 1} downto 0);")
        lines.append("    dout   : out std_logic_vector(7 downto 0)")
    lines.append("  );")
    lines.append("end entity;")
    lines.append("")
    lines.append(f"architecture rtl of {name} is")
    lines.append(f"  type rom_t is array (0 to {size - 1}) of std_logic_vector(7 downto 0);")
    lines.append("  signal rom : rom_t := (")
    # 16 bytes per source line for readability.
    body: list[str] = []
    for off in range(0, size, 16):
        chunk = data[off:off + 16]
        vals = ", ".join(f'x"{b:02X}"' for b in chunk)
        sep = "," if off + 16 < size else ""
        body.append(f"    {vals}{sep}")
    lines.extend(body)
    lines.append("  );")
    lines.append("  attribute rom_style : string;")
    lines.append('  attribute rom_style of rom : signal is "block";')
    lines.append("begin")
    lines.append("  process(clk)")
    lines.append("  begin")
    lines.append("    if rising_edge(clk) then")
    if dual:
        lines.append("      a_dout <= rom(to_integer(unsigned(a_addr)));")
        lines.append("      b_dout <= rom(to_integer(unsigned(b_addr)));")
    else:
        lines.append("      dout <= rom(to_integer(unsigned(addr)));")
    lines.append("    end if;")
    lines.append("  end process;")
    lines.append("end architecture;")
    return "\n".join(lines)


def main() -> int:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    blocks: list[str] = []
    header = [
        "-- C64 system ROMs (BASIC, KERNAL, character generator).",
        "-- GENERATED by tools/build_c64_roms.py from roms/c64/*.ROM -- do not edit by hand.",
        "-- Original Commodore ROM images are NOT redistributed with this repo; the user",
        "-- supplies them in roms/c64/ and regenerates this file locally.",
        "",
    ]
    blocks.append("\n".join(header))
    for name, fname, expect in ROMS:
        path = ROM_DIR / fname
        data = path.read_bytes()
        if len(data) != expect:
            raise SystemExit(
                f"{fname}: expected {expect} bytes, got {len(data)}"
            )
        # chargen is read by both the CPU (charset copy) and the VIC -> dual port.
        blocks.append(emit_rom(name, data, dual=(name == "chargen_rom")))
    OUT.write_text("\n\n".join(blocks) + "\n", encoding="ascii", newline="\n")
    total = sum(expect for _, _, expect in ROMS)
    print(f"wrote {OUT.relative_to(ROOT)} ({total} bytes of ROM in 3 entities)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
