#!/usr/bin/env python3
"""Build the C64 native-core hardware diagnostic ROM and regenerate
rtl/c64/c64_roms.vhd with it in the KERNAL slot (replacing the real KERNAL).

The diagnostic (sw/c64diag.s) boots straight from reset with no KERNAL/BASIC
and probes the hardware on-screen. BASIC is zero-filled (the diagnostic never
calls it); the real character generator is kept so text displays.

    python tools/build_c64_diag.py        # -> diagnostic build
    python tools/build_c64_roms.py        # <- restore the real BASIC+KERNAL
"""
from __future__ import annotations

import subprocess
from pathlib import Path

from build_c64_roms import emit_rom  # reuse the VHDL block-ROM emitter

ROOT = Path(__file__).resolve().parents[1]
SW = ROOT / "sw" / "c64"
ROM_DIR = ROOT / "roms" / "c64"
OUT = ROOT / "rtl" / "c64" / "c64_roms.vhd"


def run(cmd: list[str]) -> None:
    print("  $", " ".join(cmd))
    subprocess.run(cmd, cwd=SW, check=True)


def main() -> int:
    obj = "c64diag.o"
    diag = ROM_DIR / "DIAG.ROM"
    ROM_DIR.mkdir(parents=True, exist_ok=True)

    run(["ca65", "--cpu", "6502", "-o", obj, "c64diag.s"])
    run(["ld65", "-C", "c64diag.cfg", "-o", str(diag), obj])

    kernal = diag.read_bytes()
    if len(kernal) != 0x2000:
        raise SystemExit(f"DIAG.ROM is {len(kernal)} bytes, expected 8192")

    chargen = (ROM_DIR / "CHAR.ROM").read_bytes()
    if len(chargen) != 0x1000:
        raise SystemExit(f"CHAR.ROM is {len(chargen)} bytes, expected 4096")

    basic_path = ROM_DIR / "BASIC.ROM"
    basic = basic_path.read_bytes() if basic_path.exists() else bytes(0x2000)
    if len(basic) != 0x2000:
        basic = (basic + bytes(0x2000))[:0x2000]

    blocks = [
        "\n".join([
            "-- C64 system ROMs -- DIAGNOSTIC build.",
            "-- GENERATED by tools/build_c64_diag.py: kernal_rom = sw/c64diag.s",
            "-- (boots a polled hardware self-test), basic_rom unused, chargen_rom",
            "-- = the real CHAR.ROM. Re-run tools/build_c64_roms.py to restore the",
            "-- real BASIC + KERNAL.",
            "",
        ]),
        emit_rom("basic_rom", basic),
        emit_rom("kernal_rom", kernal),
        emit_rom("chargen_rom", chargen, dual=True),
    ]
    OUT.write_text("\n\n".join(blocks) + "\n", encoding="ascii", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)} (kernal_rom = diagnostic, {len(kernal)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
